apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mernspace-auth-cert
spec:
  secretName: auth-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: api-pizza.adityavyas.com
  dnsNames:
  - api-pizza.adityavyas.com
