apiVersion: cert-manager.io/v1
kind: Certificate 
metadata:
  name: mernspace-admin-cert
spec:
  secretName: admin-tls 
  issuerRef:
    name: letsencrypt-prod 
    kind: ClusterIssuer
  commonName: admin.adityavyas.com
  dnsNames:
  - admin.adityavyas.com